// This file is generated by `drift_dev` and should not be modified manually.
// You should instead use `drift_dev build-web` to update this file.
// If you're not using a build system, you can get a pre-built version from
// the web-example folder of the drift repository, or from the pre-built archives
// on the release page.
'use strict';
var Module = {};
var ready;
var whenReady = new Promise(function (resolve) {
  ready = resolve;
});
var result;
self.onmessage = function (e) {
  var data = e.data;
  var port = e.ports[0];
  if (data.hasOwnProperty('wasmModule')) {
    Module.wasmModule = data.wasmModule;
    return;
  }
  if (!result) {
    result = new Promise(function (resolve) {
      var worker = data.worker;
      if (worker) {
        importScripts(worker);
      }
      resolve();
    });
  }
  result = result.then(function () {
    return self.DriftWorker(data).then(function (result) {
      port.postMessage(result);
    });
  });
  result.catch(function (e) {
    var message = {
      error: e.toString()
    };
    if (e.stack) {
      message.stack = e.stack;
    }
    port.postMessage(message);
  });
};